import type { NextPage } from 'next'
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import CreateToken from '../components/CreateToken'
import { Button } from '@mui/material';



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DFS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1 className={styles.title}>
          Welcome to DFS
        </h1>
      </header>

      <main className={styles.main}>

        <div className={styles.grid}>
          <WalletMultiButton />
        </div>
        <CreateToken />
      </main>
    </div>
  )
}

export default Home
